excluded:
  - Pods
  - .build
  - DerivedData

disabled_rules:
  - trailing_whitespace
  - todo

opt_in_rules:
  - array_init
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - fallthrough
  - fatal_error_message
  - first_where
  - force_unwrapping
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - xct_specific_matcher
  - yoda_condition

analyzer_rules:
  - unused_declaration
  - unused_import

line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 350
  error: 500

file_length:
  warning: 350
  error: 500

function_body_length:
  warning: 50
  error: 100

type_name:
  min_length: 3
  max_length: 50

identifier_name:
  min_length: 2
  max_length: 50
  excluded:
    - id
    - vm
    - vc
    - to
    - at
    - of
    - up
    - x
    - y
    - i
    - j

nesting:
  type_level:
    warning: 2
    error: 3

cyclomatic_complexity:
  warning: 10
  error: 20

custom_rules:
  mark_spacing:
    name: "Mark Spacing"
    regex: '// MARK: -[a-zA-Z0-9]'
    message: "There should be a space after the MARK: -"
    severity: warning

  empty_line_after_mark:
    name: "Empty Line After Mark"
    regex: '// MARK: -[^\n]*\n[^\n]'
    message: "There should be an empty line after a MARK comment"
    severity: warning

  empty_line_before_mark:
    name: "Empty Line Before Mark"
    regex: '[^\n]\n// MARK:'
    message: "There should be an empty line before a MARK comment"
    severity: warning 